### ISSUE TITLE
Unable to deploy notebook or tensorboard servers

### ISSUE THREAD

**Issue by DanielLund** [awslabs/kubeflow-manifests#119]
**Describe the bug**
When trying to setup a notebook server or a tensorboard server when deploying kubeflow on eks I get the following error:
[403] Could not find CSRF cookie XSRF-TOKEN in the request.

**Steps To Reproduce**
Follow the Vanilla guide for v1.3 aws deployment of kubeflow

**Expected behavior**
Expected behaviour was to deploy a notebook or tensorboard server

**Environment**
* Kubernetes version 1.19
* Using EKS: Latest
* None, was deployed using an EC2 instance however

**Screenshots**

**Additional context**
I assume this isn't working because the load balancer provides http not https and that is why it is failing. I see posts about similar where they use APP_SECURE_COOKIES=false or something similar. However it doesn't say where to put that. I assume in the env file?

**Comment by DanielLund** [comment]
<img width="1440" alt="Screenshot 2022-03-03 at 11 25 54" src="https://user-images.githubusercontent.com/75539890/156555630-8253c240-2e6c-49e6-bc25-02ac4577824b.png">

**Comment by DanielLund** [comment]
This is actually urgent for me. I would love a response if possible

**Comment by surajkota** [comment]
Hi @DanielLund, looking into this. I was able to reproduce the issue

**Comment by surajkota** [comment]
Since the load balancer endpoint is not using HTTPS, the solution as the documentation suggests is to set `APP_SECURE_COOKIES: false` in all the respective webapp deployments. for e.g. in this case you would change in the jupyter-web-app deployment

`kubectl edit deployments -n kubeflow jupyter-web-app-deployment`

under `spec.template.spec.containers.env` add the environment variable
```
- env:
  - name: APP_SECURE_COOKIES
    value: "false"
```

and restart the deployment for the changes to take effect
`kubectl -n kubeflow rollout restart deployment/jupyter-web-app-deployment`

However, this approach is insecure and I would not recommend this to use in production. Next step is to document how to expose the deployment over HTTPS. I will update #67

**Comment by surajkota** [comment]
Hi @DanielLund, Please find the updated documentation here - https://github.com/awslabs/kubeflow-manifests/issues/67#issuecomment-1059566247

**Comment by DanielLund** [comment]
@surajkota I cannot thank you enough for this. This is fantastic
