### ISSUE TITLE
Missing metrics data in RDS while using KFPv2

### ISSUE THREAD

**Issue by surajkota** [awslabs/kubeflow-manifests#328]
**Describe the bug**
[Vishnu Paspunoor](https://app.slack.com/team/U03L86YGSQH)
  [12:33 AM](https://kubeflow.slack.com/archives/CKBA5D0MU/p1660635199418229)
Hi all,
I'm using kubeflow with rds, s3 and cognito. Any idea how to upload the pipeline metrics into RDS in KFP SDK v2? I could see the metrics in the run_metrics table when I tried v1 but there are no entries while using scalar metrics in v2.
v1 example: https://www.kubeflow.org/docs/components/pipelines/sdk/pipelines-metrics/
v2 example: https://www.kubeflow.org/docs/components/pipelines/sdk-v2/python-function-components/#example-python-function-based-component
Tried this too
https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/#scalar-metrics
Additionally, the run outputs tab doesn't show any data in v2

**Steps To Reproduce**

**Expected behavior**

**Environment**
* Kubernetes version
* Using EKS (yes/no), if so version?
* Kubeflow version
* AWS build number
* AWS service targeted (S3, RDS, etc.)

**Screenshots**

**Additional context**

**Comment by vishnuisu** [comment]
Here are some additional details 

**Steps To Reproduce**

Execute these examples in kubeflow and query the run_metrics table in the mlpipeline database on RDS mysql

**Expected behavior**

Run metrics are expected to be present in the run_metrics table

Environment

Kubernetes version: 1.21
Using EKS (yes/no), if so version? yes 1.21
Kubeflow version: 1.51
AWS build number
AWS service targeted (S3, RDS, etc.): RDS
Screenshots
If applicable, add screenshots to help explain your problem.

Additional context
Add any other context about the problem here.

**Comment by ryansteakley** [comment]
@vishnuisu I will attempt to re-create this behavior and get back to you asap

**Comment by ryansteakley** [comment]
@vishnuisu From what I'm seeing looks like metrics are not supported in v2 https://github.com/kubeflow/pipelines/issues/6132
