### ISSUE TITLE
Investigate why controller is mutating IAM policy 

### ISSUE THREAD

**Issue by goswamig** [awslabs/kubeflow-manifests#43]
https://github.com/kubeflow/kubeflow/blob/d43aee19ad8b556273a627ad34367e7e56b5c97e/components/profile-controller/controllers/plugin_iam.go#L128-L182

**Comment by goswamig** [comment]
customer related issue: https://github.com/kubeflow/kubeflow/issues/6166

**Comment by surajkota** [comment]
I think [this](https://github.com/kubeflow/manifests/blob/v1.2-branch/aws/infra_configs/iam_profile_controller_policy.json) was the policy which was attached to profile controller to execute the aws iam plugin

**Comment by goswamig** [comment]
@surajkota do we know which policy its attaching to?

**Comment by goswamig** [comment]
@rrrkharse @surajkota  can u guys confirm, to me it looks like that plugin of updating the role policy is optional only if plugin is added in profile.

Take a look at the sample profile https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/config/samples/profile_v1_aws_iam.yaml#L9

**Comment by surajkota** [comment]
Thanks for the investigation. The links above show how to do it, but I could find documentation on the the user story. Can you help fill in the following blanks:

As a Kubeflow user, I want to ____, so that I can _______. To do this, I need an IAM role attached in the ___, ___, ___ service accounts in a user profile namespace. I can use the `AwsIamForServiceAccount` plugin in Kubeflow profiles to provide an IAM role in the profile CR. This IAM role needs to be configured with _____ permissions and needs to have a trust policy for the ______ namespaces and  _______ service accounts. For this plugin to work, the `profile-controller-service-account` needs to be annotated with an IAM role with the permissions as described in this [policy](https://github.com/kubeflow/manifests/blob/v1.2-branch/aws/infra_configs/iam_profile_controller_policy.json)

We need more information about what this IAM role can be used for, what permissions does this role need etc. e.g.: which service accounts does this role get attached to? notebooks? pipeline runs? etc.

**Comment by goswamig** [comment]
plugin documentation: https://github.com/kubeflow/kubeflow/tree/d43aee19ad8b556273a627ad34367e7e56b5c97e/components/profile-controller

A complete sample of profile: https://github.com/kubeflow/kubeflow/blob/d43aee19ad8b556273a627ad34367e7e56b5c97e/components/profile-controller/config/samples/profile_v1beta1_profile.yaml

should  `gcpServiceAccount` replace by `AwsIamForServiceAccount `.

**Comment by goswamig** [comment]
we need to test it for all kubeflow component.

**Comment by surajkota** [comment]
This was related to `AwsIamForServiceAccount` plugin in profiles https://awslabs.github.io/kubeflow-manifests/docs/component-guides/profiles/#profile-plugins. Investigation is complete and feature is released now
