### ISSUE TITLE
Error: deleting S3 Bucket (kf-artifact-store-***): BucketNotEmpty: The bucket you tried to delete is not empty

### ISSUE THREAD

**Issue by namnd00** [awslabs/kubeflow-manifests#519]
**Describe the bug**
When I use the terraform source code in [link](https://github.com/awslabs/kubeflow-manifests/tree/main/deployments/rds-s3/terraform) to uninstall Kubeflow on AWS with a command. 

**Steps To Reproduce**

```sh
make delete
```
The bug is:
```sh
Error: deleting S3 Bucket (kf-artifact-store-***): BucketNotEmpty: The bucket you tried to delete is not empty
status code: 409, request id:***, host id: ***
Makefile:47: recipe for target 'delete-kubeflow-components' failed
make: *** [delete-kubeflow-components] Error 1
```

**Expected behavior**
I expected to resolve how to delete s3 bucket if it's empty

**Environment**
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? yes, 1.21
* Kubeflow version: 1.6
* AWS build number: 
* AWS service targeted (S3, RDS, etc.): fails on S3-RDS

**Screenshots**
![Screen Shot 2022-12-06 at 09 59 22](https://user-images.githubusercontent.com/38483189/205799831-ecae2cfe-b8e7-422a-89ee-37c88a679bf0.png)

**Comment by surajkota** [comment]
Hi @namnd00 , thanks for reporting the issue. This is expected behavior. You will have to set the [force_destroy_s3_bucket variable](https://github.com/awslabs/kubeflow-manifests/blob/main/deployments/rds-s3/terraform/variables.tf#L147) to true for deleting a non empty bucket. Can you check if you have set it to true?
