### ISSUE TITLE
Kubeflow logout stuck in infinite loop

### ISSUE THREAD

**Issue by harmeet-singh-discovery** [awslabs/kubeflow-manifests#62]
**Describe the bug**

I installed Kubeflow 1.4 using Cognito. I can access the Kubeflow UI and signin properly. When I click on logout button, it get stuck in infinite loop. As a result, user is not logged out.

**Steps To Reproduce**
1- Install Kubeflow from this guide: https://github.com/awslabs/kubeflow-manifests/tree/v1.4-branch/distributions/aws/examples/cognito
2- Sign in via Kubeflow UI
3- Logout via Kubeflow UI

**Expected behavior**
I expect user to be logged out and redirected to sign-in page

**Additional context**
This bug is related to the feature: https://github.com/kubeflow/kubeflow/pull/5174

**Comment by surajkota** [comment]
Thanks for reporting the issue.
A workaround until this issue is resolved is to use an incognito window(Chrome)/private window(Firefox) to login to Kubeflow dashboard and close the window when user wants to logout. This works because the browser clears the cookies when the window is closed.

**Comment by ryansteakley** [comment]
Hey Harmeet, I took a look into tackling this issue. It is not a bug since the kubeflow dashboards logout functionality is tied to "logout will initiate /logout which was implemented in oidc-authservice" which we are not utilizing/installing for our cognito example. To properly logout a user when using Cognito + AWS ALB is for the ALB cookies to be expired and then for the Cognito logout endpoint url to be hit.  These ALB cookies are Http-only and secure so they can only be delete server-side.

- Currently have a istio VirtualService which allows for logout only once however subsequent logouts will not clear the cookies and only hit the redirect and not clear the cookies. However if the user manually deletes the cookies using their browsers console they can click on the logout button and be properly logged out.

I am currently working on writing a micro-service to handle the logout logic here, but am open to any suggestions or guidance of anyone who has more experience/knowledge of Istio/Envoy here which may make this easier.
