### ISSUE TITLE
Add the ability to read from S3 using vanilla terraform deployment

### ISSUE THREAD

**Issue by RegaliaXYZ** [awslabs/kubeflow-manifests#733]
**Is your feature request related to a problem? Please describe.**
Currently when deploying a vanilla terraform kubeflow installation, it cannot read from S3 as it seems to not have the necessary permissions

**Describe the solution you'd like**
A flag to allow S3 reading from kubeflow without having to install using the rds-s3-terraform manifests as it creates another bucket for artifacts. Or a list of permissions that would be passed to kubeflow

**Describe alternatives you've considered**
Using rds-s3 with rds disabled works, but it creates the artifact bucket which is not something im interested in having

**Comment by surajkota** [comment]
Hi @RegaliaXYZ, are you just looking to access any S3 bucket from your profile?

If so, checkout the `AwsIamForServiceAccount` plugin for profile - https://awslabs.github.io/kubeflow-manifests/docs/component-guides/profiles/

If this not address your need, please provide more details on the usecase

**Comment by RegaliaXYZ** [comment]
Is there any documentation on how to apply that using terraform? I'm not looking to manually create roles & permissions

**Comment by surajkota** [comment]
High level there are 2 steps to use this feature:
1. Configuring the permissions for the profile controller - This is already configured by default in terraform blueprints that this repository provides. If you used it, no additional steps are required
2. Creating a role for the user and providing appropriate permissions

For 2, here is a sample terraform code:
- create the role - https://github.com/awslabs/kubeflow-manifests/blob/main/deployments/rds-s3/terraform/rds-s3-components/main.tf#L93-L106
- pass the role ARN to user-namespace module - https://github.com/awslabs/kubeflow-manifests/blob/main/deployments/rds-s3/terraform/rds-s3-components/main.tf#L402-L417

Note: I recommend creating a new profile for this since the terraform helm addon has a limitation where it does not detect changes to helm values - https://github.com/hashicorp/terraform-provider-helm/issues/346. We have heard from users that they [incremented the chart version](https://github.com/awslabs/kubeflow-manifests/blob/main/charts/common/user-namespace/Chart.yaml#L6) to get around this issue.
